#I know this solution is janky as hell,
# but I had to finish this part of the
# assignment to get some more insight.

server.port=28852
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true